### ISSUE TITLE
Can't install this package using pip

### ISSUE THREAD

**Issue by mgmacias95** [davidgasquez/sqline#1]
Hello @davidgasquez,

I tried to install the package using `pip` but I've got the following error:
```shellsession
$ pip install sqline
Collecting sqline
  Could not find a version that satisfies the requirement sqline (from versions: )
No matching distribution found for sqline
$ pip3 install sqline
Collecting sqline
  Could not find a version that satisfies the requirement sqline (from versions: )
No matching distribution found for sqline
```

I'm using ubuntu server 16.04.

**EDIT:** I've installed it using the following [command](https://medium.com/@lynzt/install-python-packages-from-github-5866d234c4e4):
```shellsession
$ pip install --upgrade git+git://github.com/davidgasquez/sqline.git
```

Best regards,
Marta

**Comment by davidgasquez** [comment]
Hey @mgmacias95! Thanks for opening the issue, somewhat I removed the build package from Pypi! 🙈

I've added [TravisCI integration](https://travis-ci.org/davidgasquez/sqline/builds/285120325) to this project (and a shiny badge) so each commit to master will update the package in Pypi. 

This should fix the issue for the moment! 😉

**Comment by mgmacias95** [comment]
Hey @davidgasquez,

just tried to install the package again and it worked ok! 😉 

Thank you so much,
Marta
